package shim

import (
	"runtime"
	"strings"
)

// Mode is how a shim submits: blocking by default, or one of the two passive
// modes that submit and get out of the way.
type Mode string

const (
	// ModeBlocking checks the install and refuses it on malware. The default.
	ModeBlocking Mode = ""
	// ModeWatchdog submits a passive scan using the machine's own login or API
	// key and forwards the install without waiting for a verdict.
	ModeWatchdog Mode = "watchdog"
	// ModeMonitor submits through a monitor's ingest token, so the machine needs
	// no credential of its own. Carries MonitorID.
	ModeMonitor Mode = "monitor"
)

// ScriptOptions describes one shim to generate.
type ScriptOptions struct {
	Manager   string
	Dir       string
	Binary    string
	Mode      Mode
	MonitorID string
}

// Script renders the shim for one package manager.
func Script(o ScriptOptions) string {
	if runtime.GOOS == "windows" {
		return windowsScript(o)
	}
	return posixScript(o)
}

// modeEnv renders the env-var block a passive shim exports before exec'ing.
//
// The monitor id reaches here already validated (`client.ValidIngestToken`, via
// ValidateMode) and is shell-quoted on top: it is attacker-shaped input being
// written into an executable file, so neither guard is the only one.
func modeEnv(o ScriptOptions, quote func(string) string, assign func(k, v string) string) string {
	switch o.Mode {
	case ModeWatchdog:
		return assign(passiveEnv, "1")
	case ModeMonitor:
		return assign(passiveEnv, "1") + assign(monitorEnv, quote(o.MonitorID))
	default:
		return ""
	}
}

func posixScript(o ScriptOptions) string {
	r := strings.NewReplacer(
		"{{MANAGER}}", o.Manager,
		"{{DIR}}", shellQuote(o.Dir),
		"{{BIN}}", shellQuote(o.Binary),
		"{{BINRAW}}", o.Binary,
		"{{MARKER}}", Marker,
		"{{BINPREFIX}}", binPrefix,
		"{{BYPASS}}", BypassEnv,
		"{{MODELINE}}", modeHeader(o),
		"{{MODEENV}}", modeEnv(o, shellQuote, func(k, v string) string {
			return k + "=" + v + "\nexport " + k + "\n"
		}),
	)
	return r.Replace(posixTemplate)
}

// modeHeader records the mode in the shim's own header, so `shim status` can
// report it and a re-run of `shim install` can see what it is replacing.
func modeHeader(o ScriptOptions) string {
	if o.Mode == ModeBlocking {
		return ""
	}
	if o.Mode == ModeMonitor {
		return modePrefix + string(o.Mode) + " " + o.MonitorID
	}
	return modePrefix + string(o.Mode)
}

const posixTemplate = `#!/bin/sh
# ossprey shim for ` + "`{{MANAGER}}`" + ` — generated by ` + "`ossprey shim install`" + `. Do not edit.
#
# {{MARKER}}
# {{BINPREFIX}}{{BINRAW}}
# {{MODELINE}}
#
# Why does {{MANAGER}} behave differently here? This script sits earlier on your
# PATH than the real {{MANAGER}}, so that installs are checked for malware before
# they run. Everything else (` + "`{{MANAGER}} run`" + `, version queries, ...) is passed
# straight through untouched.
#
#   ossprey shim status      what is installed, and where the real {{MANAGER}} lives
#   ossprey shim uninstall   remove the shims and undo the PATH change
#   {{BYPASS}}=1 {{MANAGER}} ...   skip the check for one command

# -f disables pathname expansion: the PATH loop below iterates unquoted, and a
# PATH entry containing a glob character would otherwise be rewritten into
# whatever it happens to match.
set -uf

ossprey_shim_dir={{DIR}}
ossprey_bin={{BIN}}

# Recursion guard: drop our own directory from PATH so that the exec below — and
# ossprey's own lookup of the real {{MANAGER}} — find the genuine tool, not this
# script again.
ossprey_newpath=''
ossprey_oldifs=$IFS
IFS=':'
for ossprey_entry in $PATH; do
	if [ "$ossprey_entry" = "$ossprey_shim_dir" ]; then
		continue
	fi
	if [ -z "$ossprey_newpath" ]; then
		ossprey_newpath=$ossprey_entry
	else
		ossprey_newpath=$ossprey_newpath:$ossprey_entry
	fi
done
IFS=$ossprey_oldifs
PATH=$ossprey_newpath
export PATH
unset ossprey_newpath ossprey_oldifs ossprey_entry ossprey_shim_dir

# Fail open, always. A scanner that can break ` + "`npm install`" + ` when it is having a
# bad day is a scanner people rip out.
if [ -n "${{{BYPASS}}:-}" ]; then
	exec {{MANAGER}} "$@"
fi
if [ ! -x "$ossprey_bin" ]; then
	echo "ossprey: shim: $ossprey_bin is missing; running {{MANAGER}} unchecked." >&2
	echo "ossprey: reinstall ossprey, or run 'ossprey shim uninstall' to remove the shims." >&2
	exec {{MANAGER}} "$@"
fi

{{MODEENV}}exec "$ossprey_bin" {{MANAGER}} "$@"
`

func windowsScript(o ScriptOptions) string {
	r := strings.NewReplacer(
		"{{MANAGER}}", o.Manager,
		"{{DIR}}", strings.TrimSuffix(o.Dir, `\`),
		"{{BIN}}", o.Binary,
		"{{BINRAW}}", o.Binary,
		"{{MARKER}}", Marker,
		"{{BINPREFIX}}", binPrefix,
		"{{BYPASS}}", BypassEnv,
		"{{MODELINE}}", modeHeader(o),
		"{{MODEENV}}", modeEnv(o, func(v string) string { return v }, func(k, v string) string {
			return "set \"" + k + "=" + v + "\"\n"
		}),
	)
	return r.Replace(windowsTemplate)
}

const windowsTemplate = `@echo off
:: ossprey shim for {{MANAGER}} — generated by "ossprey shim install". Do not edit.
::
:: {{MARKER}}
:: {{BINPREFIX}}{{BINRAW}}
:: {{MODELINE}}
::
:: Why does {{MANAGER}} behave differently here? This script sits earlier on your
:: PATH than the real {{MANAGER}}, so that installs are checked for malware before
:: they run. Everything else is passed straight through untouched.
::
::   ossprey shim status      what is installed, and where the real {{MANAGER}} lives
::   ossprey shim uninstall   remove the shims and undo the PATH change
::   set {{BYPASS}}=1         skip the check for this shell session
setlocal

:: Recursion guard: drop our own directory from PATH so the real {{MANAGER}} is what
:: gets found downstream. The trailing ";" makes the last PATH entry match too.
set "PATH=%PATH%;"
call set "PATH=%%PATH:{{DIR}};=%%"

if defined {{BYPASS}} goto ossprey_bypass
if not exist "{{BIN}}" (
	echo ossprey: shim: "{{BIN}}" is missing; running {{MANAGER}} unchecked.>&2
	goto ossprey_bypass
)

{{MODEENV}}"{{BIN}}" {{MANAGER}} %*
exit /b %ERRORLEVEL%

:ossprey_bypass
call {{MANAGER}} %*
exit /b %ERRORLEVEL%
`

func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}
