package shim

import (
	"runtime"
	"strings"
)

// Script renders the shim for manager, calling the ossprey binary at binPath
// and living in dir. Rendering is pure so tests can assert on the text without
// touching a filesystem.
//
// The header is load-bearing UX, not decoration: the single most likely support
// question this feature generates is "why is npm behaving strangely?", and the
// answer needs to be in the first thing a confused developer opens.
func Script(manager, dir, binPath string) string {
	if runtime.GOOS == "windows" {
		return windowsScript(manager, dir, binPath)
	}
	return posixScript(manager, dir, binPath)
}

func posixScript(manager, dir, binPath string) string {
	r := strings.NewReplacer(
		"{{MANAGER}}", manager,
		"{{DIR}}", shellQuote(dir),
		"{{BIN}}", shellQuote(binPath),
		"{{BINRAW}}", binPath,
		"{{MARKER}}", Marker,
		"{{BINPREFIX}}", binPrefix,
		"{{BYPASS}}", BypassEnv,
	)
	return r.Replace(posixTemplate)
}

const posixTemplate = `#!/bin/sh
# ossprey shim for ` + "`{{MANAGER}}`" + ` — generated by ` + "`ossprey shim install`" + `. Do not edit.
#
# {{MARKER}}
# {{BINPREFIX}}{{BINRAW}}
#
# Why does {{MANAGER}} behave differently here? This script sits earlier on your
# PATH than the real {{MANAGER}}, so that installs are checked for malware before
# they run. Everything else (` + "`{{MANAGER}} run`" + `, version queries, ...) is passed
# straight through untouched.
#
#   ossprey shim status      what is installed, and where the real {{MANAGER}} lives
#   ossprey shim uninstall   remove the shims and undo the PATH change
#   {{BYPASS}}=1 {{MANAGER}} ...   skip the check for one command

# -f disables pathname expansion: the PATH loop below iterates unquoted, and a
# PATH entry containing a glob character would otherwise be rewritten into
# whatever it happens to match.
set -uf

ossprey_shim_dir={{DIR}}
ossprey_bin={{BIN}}

# Recursion guard: drop our own directory from PATH so that the exec below — and
# ossprey's own lookup of the real {{MANAGER}} — find the genuine tool, not this
# script again.
ossprey_newpath=''
ossprey_oldifs=$IFS
IFS=':'
for ossprey_entry in $PATH; do
	if [ "$ossprey_entry" = "$ossprey_shim_dir" ]; then
		continue
	fi
	if [ -z "$ossprey_newpath" ]; then
		ossprey_newpath=$ossprey_entry
	else
		ossprey_newpath=$ossprey_newpath:$ossprey_entry
	fi
done
IFS=$ossprey_oldifs
PATH=$ossprey_newpath
export PATH
unset ossprey_newpath ossprey_oldifs ossprey_entry ossprey_shim_dir

# Fail open, always. A scanner that can break ` + "`npm install`" + ` when it is having a
# bad day is a scanner people rip out.
if [ -n "${{{BYPASS}}:-}" ]; then
	exec {{MANAGER}} "$@"
fi
if [ ! -x "$ossprey_bin" ]; then
	echo "ossprey: shim: $ossprey_bin is missing; running {{MANAGER}} unchecked." >&2
	echo "ossprey: reinstall ossprey, or run 'ossprey shim uninstall' to remove the shims." >&2
	exec {{MANAGER}} "$@"
fi

exec "$ossprey_bin" {{MANAGER}} "$@"
`

func windowsScript(manager, dir, binPath string) string {
	r := strings.NewReplacer(
		"{{MANAGER}}", manager,
		"{{DIR}}", strings.TrimSuffix(dir, `\`),
		"{{BIN}}", binPath,
		"{{BINRAW}}", binPath,
		"{{MARKER}}", Marker,
		"{{BINPREFIX}}", binPrefix,
		"{{BYPASS}}", BypassEnv,
	)
	return r.Replace(windowsTemplate)
}

const windowsTemplate = `@echo off
:: ossprey shim for {{MANAGER}} — generated by "ossprey shim install". Do not edit.
::
:: {{MARKER}}
:: {{BINPREFIX}}{{BINRAW}}
::
:: Why does {{MANAGER}} behave differently here? This script sits earlier on your
:: PATH than the real {{MANAGER}}, so that installs are checked for malware before
:: they run. Everything else is passed straight through untouched.
::
::   ossprey shim status      what is installed, and where the real {{MANAGER}} lives
::   ossprey shim uninstall   remove the shims and undo the PATH change
::   set {{BYPASS}}=1         skip the check for this shell session
setlocal

:: Recursion guard: drop our own directory from PATH so the real {{MANAGER}} is what
:: gets found downstream. The trailing ";" makes the last PATH entry match too.
set "PATH=%PATH%;"
call set "PATH=%%PATH:{{DIR}};=%%"

if defined {{BYPASS}} goto ossprey_bypass
if not exist "{{BIN}}" (
	echo ossprey: shim: "{{BIN}}" is missing; running {{MANAGER}} unchecked.>&2
	goto ossprey_bypass
)

"{{BIN}}" {{MANAGER}} %*
exit /b %ERRORLEVEL%

:ossprey_bypass
call {{MANAGER}} %*
exit /b %ERRORLEVEL%
`

// shellQuote renders s as a single-quoted POSIX shell word.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}
