// Package setup holds the reusable pieces of `ossprey init`: generating a CI
// workflow file and naming the API key it will use. The interactive
// orchestration (login, key creation, first scan) lives in cmd/ossprey.
package setup

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// WorkflowRelPath is where the generated GitHub Actions workflow lands,
// relative to the project root.
const WorkflowRelPath = ".github/workflows/ossprey.yml"

// workflowTemplate is the GitHub Actions workflow dropped by `ossprey init`.
// %s is the default branch name. It matches the README's "CI usage" section:
// install the CLI, scan the checkout, fail the build on a malware verdict.
const workflowTemplate = `# Generated by "ossprey init". Scans dependencies for supply-chain malware.
# Requires the OSSPREY_API_KEY repository secret (ossprey init prints one).
name: Ossprey malware scan

on:
  push:
    branches: [%s]
  pull_request:

permissions:
  contents: read

jobs:
  ossprey:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ossprey
        run: |
          curl -fsSL https://github.com/ossprey/ossprey-cli/releases/latest/download/install.sh \
            | OSSPREY_INSTALL_DIR="$HOME/.local/bin" sh
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      - name: Ossprey scan
        env:
          OSSPREY_API_KEY: ${{ secrets.OSSPREY_API_KEY }}
        run: ossprey scan .
`

// WriteWorkflow writes the CI workflow under dir, creating .github/workflows
// as needed. It never overwrites: if the file already exists it returns
// created=false and leaves it untouched, so re-running init is safe.
func WriteWorkflow(dir, defaultBranch string) (path string, created bool, err error) {
	path = filepath.Join(dir, filepath.FromSlash(WorkflowRelPath))
	if _, err := os.Stat(path); err == nil {
		return path, false, nil
	} else if !os.IsNotExist(err) {
		return path, false, fmt.Errorf("stat %s: %w", path, err)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return path, false, fmt.Errorf("create workflows dir: %w", err)
	}
	content := fmt.Sprintf(workflowTemplate, defaultBranch)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return path, false, fmt.Errorf("write workflow: %w", err)
	}
	return path, true, nil
}

// DefaultBranch returns the repository's default branch for dir, best-effort:
// origin's HEAD if known, else the current branch, else "main".
func DefaultBranch(dir string) string {
	// refs/remotes/origin/HEAD tracks the remote's default branch when cloned.
	if out, err := gitOutput(dir, "symbolic-ref", "--short", "refs/remotes/origin/HEAD"); err == nil {
		if branch := strings.TrimPrefix(out, "origin/"); branch != "" {
			return branch
		}
	}
	if out, err := gitOutput(dir, "branch", "--show-current"); err == nil && out != "" {
		return out
	}
	return "main"
}

func gitOutput(dir string, args ...string) (string, error) {
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	out, err := cmd.Output()
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(string(out)), nil
}

// GenerateKeyName returns a fresh CI key name like "ci-a1b2c3d4". It stays
// within the API's constraints (max 20 chars, no whitespace) and the random
// suffix keeps re-runs of init from colliding with earlier keys.
func GenerateKeyName() string {
	b := make([]byte, 4)
	if _, err := rand.Read(b); err != nil {
		// crypto/rand failing is effectively fatal elsewhere; a fixed name
		// still works (the API rejects duplicates and init retries).
		return "ci-ossprey-init"
	}
	return "ci-" + hex.EncodeToString(b)
}
