// Package setup holds the reusable pieces of `ossprey init`: generating a CI
// workflow file and naming the API key it will use. The interactive
// orchestration (login, key creation, first scan) lives in cmd/ossprey.
package setup

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// WorkflowRelPath is where the generated GitHub Actions workflow lands,
// relative to the project root.
const WorkflowRelPath = ".github/workflows/ossprey.yml"

// workflowTemplate is the GitHub Actions workflow dropped by `ossprey init`.
// %s is the default branch name, already YAML-quoted by yamlQuote. It matches
// the README's "CI usage" section: install the CLI, scan the checkout, fail the
// build on a malware verdict.
const workflowTemplate = `# Generated by "ossprey init". Scans dependencies for supply-chain malware.
# Requires the OSSPREY_API_KEY repository secret (ossprey init prints one).
name: Ossprey malware scan

on:
  push:
    branches: [%s]
  pull_request:

permissions:
  contents: read

jobs:
  ossprey:
    runs-on: ubuntu-latest
    # GitHub withholds repository secrets from pull_request runs originating in a
    # fork, so OSSPREY_API_KEY would be empty and the scan would fail for a
    # missing key rather than for malware. Skip those runs instead of reporting a
    # red build no contributor can fix. Do NOT "solve" this by switching the
    # trigger to pull_request_target, which grants secrets to untrusted code.
    if: >-
      github.event_name != 'pull_request' ||
      github.event.pull_request.head.repo.full_name == github.repository
    steps:
      # Actions are pinned to a commit SHA, not a mutable tag: a tag can be
      # repointed at new code, which is the same supply-chain risk this workflow
      # exists to catch.
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Install ossprey
        run: |
          # install.sh does not create the target directory, so make it first.
          mkdir -p "$HOME/.local/bin"
          curl -fsSL https://github.com/ossprey/ossprey-cli/releases/latest/download/install.sh \
            | OSSPREY_INSTALL_DIR="$HOME/.local/bin" sh
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      - name: Ossprey scan
        env:
          OSSPREY_API_KEY: ${{ secrets.OSSPREY_API_KEY }}
        run: ossprey scan .
`

// WriteWorkflow writes the CI workflow under dir, creating .github/workflows
// as needed. It never overwrites: if the file already exists it returns
// created=false and leaves it untouched, so re-running init is safe. The
// O_EXCL create makes that guarantee atomic rather than a stat-then-write race
// that could clobber a file written in between.
func WriteWorkflow(dir, defaultBranch string) (path string, created bool, err error) {
	path = filepath.Join(dir, filepath.FromSlash(WorkflowRelPath))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return path, false, fmt.Errorf("create workflows dir: %w", err)
	}
	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o644)
	if err != nil {
		if errors.Is(err, os.ErrExist) {
			return path, false, nil
		}
		return path, false, fmt.Errorf("create workflow: %w", err)
	}
	defer f.Close()

	// A failed write must not leave a truncated file behind: the next run's
	// O_EXCL would then report "already exists; left untouched" and quietly
	// keep unparseable YAML in place.
	content := fmt.Sprintf(workflowTemplate, yamlQuote(defaultBranch))
	if _, err := f.WriteString(content); err != nil {
		os.Remove(path)
		return path, false, fmt.Errorf("write workflow: %w", err)
	}
	if err := f.Close(); err != nil {
		os.Remove(path)
		return path, false, fmt.Errorf("write workflow: %w", err)
	}
	return path, true, nil
}

// yamlQuote renders s as a YAML single-quoted scalar. Branch names are far more
// permissive than they look — git happily accepts `main]`, `a#b`, `a&b` and
// embedded quotes — and dropped raw into `branches: [%s]` any of those produce a
// workflow file YAML cannot parse. Single-quoting handles every case (only `'`
// needs escaping, by doubling); a name carrying control characters is a
// git-level impossibility, so it falls back rather than emitting something
// unparseable.
func yamlQuote(s string) string {
	if s == "" || strings.ContainsFunc(s, func(r rune) bool { return r < 0x20 || r == 0x7f }) {
		s = "main"
	}
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

// DefaultBranch returns the repository's default branch for dir, best-effort.
//
// The order matters more than it looks. The obvious shortcut — "use the branch
// we're on" — is actively wrong: `ossprey init` is exactly the sort of command
// you run from a scratch branch before touching main, and pinning the workflow's
// push trigger to that feature branch produces CI that never fires on a real
// merge. So the current branch is the *last* resort, consulted only when the
// repository offers no better answer:
//
//  1. refs/remotes/origin/HEAD — the remote's default branch, set by git clone.
//  2. a local main/master — reliable and offline; covers `git init` + `git remote
//     add`, where origin/HEAD is never written.
//  3. the current branch — only when the repo has no conventional default.
//  4. "main" — no git, no repo.
func DefaultBranch(dir string) string {
	if out, err := gitOutput(dir, "symbolic-ref", "--short", "refs/remotes/origin/HEAD"); err == nil {
		if branch := strings.TrimPrefix(out, "origin/"); branch != "" {
			return branch
		}
	}
	for _, candidate := range []string{"main", "master"} {
		for _, ref := range []string{
			"refs/heads/" + candidate,
			"refs/remotes/origin/" + candidate,
		} {
			if _, err := gitOutput(dir, "show-ref", "--verify", "--quiet", ref); err == nil {
				return candidate
			}
		}
	}
	if out, err := gitOutput(dir, "branch", "--show-current"); err == nil && out != "" {
		return out
	}
	return "main"
}

func gitOutput(dir string, args ...string) (string, error) {
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	out, err := cmd.Output()
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(string(out)), nil
}

// GenerateKeyName returns a fresh CI key name like "ci-a1b2c3d4". It stays
// within the API's constraints (max 20 chars, no whitespace) and the random
// suffix keeps re-runs of init from colliding with earlier keys.
func GenerateKeyName() string {
	b := make([]byte, 4)
	if _, err := rand.Read(b); err != nil {
		// crypto/rand failing is effectively fatal elsewhere; a fixed name
		// still works (the API rejects duplicates and init retries).
		return "ci-ossprey-init"
	}
	return "ci-" + hex.EncodeToString(b)
}
